#!/bin/bash

echo "EC2_INSTANCE_COUNT : " ${EC2_INSTANCE_COUNT}
echo "EC2_TASK_COUNT : " ${EC2_TASK_COUNT}
echo "AURORA_READ_REPLICA : " ${AURORA_READ_REPLICA}
echo "ELASTICACHE_SHADE : " ${ELASTICACHE_SHADE}
